# Imagen base con Java 17
FROM openjdk:17-jdk-slim

# Crea y define el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el jar al contenedor (sin barra inicial)
COPY target/clubes-0.0.1-SNAPSHOT.jar app.jar

# Expón el puerto correcto (ajústalo al que usa tu Spring Boot)
EXPOSE 8090

# Comando de inicio
ENTRYPOINT ["java", "-jar", "app.jar"]
